DO $$ BEGIN
	CREATE TYPE "MediaType" AS ENUM ('VIDEO', 'IMAGE');
EXCEPTION
	WHEN duplicate_object THEN null;
END $$;

ALTER TABLE "Video"
ADD COLUMN IF NOT EXISTS "type" "MediaType" NOT NULL DEFAULT 'VIDEO';
